airport_list = {

        "HIR":["Honiara", "Honiara International Airport", "SB"],
"POM":["Port Moresby", "Port Moresby Jacksons International Airport", "PG"],
"KEF":["Reykjavik", "Keflavik International Airport", "IS"],
"YEG":["Edmonton", "Edmonton International Airport", "CA"],
"YHZ":["Halifax", "Halifax / Stanfield International Airport", "CA"],
"YLW":["Kelowna", "Kelowna International Airport", "CA"],
"YOW":["Ottawa", "Ottawa Macdonald-Cartier International Airport", "CA"],
"YQB":["Quebec", "Quebec Jean Lesage International Airport", "CA"],
"YUL":["Montreal", "Montreal / Pierre Elliott Trudeau International Airport", "CA"],
"YVR":["Vancouver", "Vancouver International Airport", "CA"],
"YWG":["Winnipeg", "Winnipeg / James Armstrong Richardson International Airport", "CA"],
"YYC":["Calgary", "Calgary International Airport", "CA"],
"YYT":["St. John's", "St. John's International Airport", "CA"],
"YYZ":["Toronto", "Lester B. Pearson International Airport", "CA"],
"ALG":["Algiers", "Houari Boumediene Airport", "DZ"],
"ACC":["Accra", "Kotoka International Airport", "GH"],
"ABV":["Abuja", "Nnamdi Azikiwe International Airport", "NG"],
"LOS":["Lagos", "Murtala Muhammed International Airport", "NG"],
"NIM":["Niamey", "Diori Hamani International Airport", "NE"],
"TUN":["Tunis", "Tunis Carthage International Airport", "TN"],
"BRU":["Brussels", "Brussels Airport", "BE"],
"BER":["Berlin", "Berlin Brandenburg Airport", "DE"],
"FRA":["Frankfurt am Main", "Frankfurt am Main Airport", "DE"],
"HAM":["Hamburg", "Hamburg Helmut Schmidt Airport", "DE"],
"CGN":["Cologne", "Cologne Bonn Airport", "DE"],
"DUS":["Dusseldorf", "Dusseldorf Airport", "DE"],
"MUC":["Munich", "Munich Airport", "DE"],
"NUE":["Nuremberg", "Nuremberg Airport", "DE"],
"LEJ":["Leipzig", "Leipzig/Halle Airport", "DE"],
"STR":["Stuttgart", "Stuttgart Airport", "DE"],
"HAJ":["Hannover", "Hannover Airport", "DE"],
"TLL":["Tallinn", "Lennart Meri Tallinn Airport", "EE"],
"HEL":["Helsinki", "Helsinki Vantaa Airport", "FI"],
"BFS":["Belfast", "Belfast International Airport", "GB"],
"BHX":["Birmingham", "Birmingham International Airport", "GB"],
"MAN":["Manchester", "Manchester Airport", "GB"],
"LTN":["London", "London Luton Airport", "GB"],
"LGW":["London", "London Gatwick Airport", "GB"],
"LHR":["London", "London Heathrow Airport", "GB"],
"GLA":["Paisley, Renfrewshire", "Glasgow International Airport", "GB"],
"EDI":["Edinburgh", "Edinburgh Airport", "GB"],
"STN":["London", "London Stansted Airport", "GB"],
"AMS":["Amsterdam", "Amsterdam Airport Schiphol", "NL"],
"EIN":["Eindhoven", "Eindhoven Airport", "NL"],
"DUB":["Dublin", "Dublin Airport", "IE"],
"SNN":["Shannon", "Shannon Airport", "IE"],
"BLL":["Billund", "Billund Airport", "DK"],
"CPH":["Copenhagen", "Copenhagen Kastrup Airport", "DK"],
"LUX":["Luxembourg", "Luxembourg-Findel International Airport", "LU"],
"BGO":["Bergen", "Bergen Airport, Flesland", "NO"],
"OSL":["Oslo", "Oslo Airport, Gardermoen", "NO"],
"TOS":["Tromso", "Tromso Airport, Langnes", "NO"],
"SVG":["Stavanger", "Stavanger Airport, Sola", "NO"],
"GDN":["Gdansk", "Gdansk Lech Walesa Airport", "PL"],
"KRK":["Krakow", "Krakow John Paul II International Airport", "PL"],
"WAW":["Warsaw", "Warsaw Chopin Airport", "PL"],
"GOT":["Gothenburg", "Gothenburg-Landvetter Airport", "SE"],
"ARN":["Stockholm", "Stockholm-Arlanda Airport", "SE"],
"RIX":["Riga", "Riga International Airport", "LV"],
"VNO":["Vilnius", "Vilnius International Airport", "LT"],
"CPT":["Cape Town", "Cape Town International Airport", "ZA"],
"DUR":["Durban", "King Shaka International Airport", "ZA"],
"JNB":["Johannesburg", "OR Tambo International Airport", "ZA"],
"GBE":["Gaborone", "Sir Seretse Khama International Airport", "BW"],
"SHO":["Mpaka", "King Mswati III International Airport", "SZ"],
"MRU":["Plaine Magnein", "Sir Seewoosagur Ramgoolam International Airport", "MU"],
"LUN":["Lusaka", "Kenneth Kaunda International Airport", "ZM"],
"RUN":["St Denis", "Roland Garros Airport", "RE"],
"TNR":["Antananarivo", "Ivato Airport", "MG"],
"LAD":["Luanda", "Quatro de Fevereiro Airport", "AO"],
"MPM":["Maputo", "Maputo Airport", "MZ"],
"SEZ":["Mahe Island", "Seychelles International Airport", "SC"],
"NDJ":["N'Djamena", "N'Djamena International Airport", "TD"],
"HRE":["Harare", "Robert Gabriel Mugabe International Airport", "ZW"],
"WDH":["Windhoek", "Hosea Kutako International Airport", "NA"],
"FIH":["Kinshasa", "Ndjili International Airport", "CD"],
"BKO":["Bamako", "Modibo Keita International Airport", "ML"],
"BJL":["Banjul", "Banjul International Airport", "GM"],
"FUE":["Fuerteventura Island", "Fuerteventura Airport", "ES"],
"LPA":["Gran Canaria Island", "Gran Canaria Airport", "ES"],
"TFS":["Tenerife", "Tenerife Sur Airport", "ES"],
"FNA":["Freetown (Lungi-Town)", "Lungi International Airport", "SL"],
"ROB":["Monrovia", "Roberts International Airport", "LR"],
"CMN":["Casablanca", "Mohammed V International Airport", "MA"],
"DSS":["Dakar", "Blaise Diagne International Airport", "SN"],
"ADD":["Addis Ababa", "Addis Ababa Bole International Airport", "ET"],
"JIB":["Djibouti City", "Djibouti-Ambouli Airport", "DJ"],
"CAI":["Cairo", "Cairo International Airport", "EG"],
"HRG":["Hurghada", "Hurghada International Airport", "EG"],
"SSH":["Sharm el-Sheikh", "Sharm El Sheikh International Airport", "EG"],
"JUB":["Juba", "Juba International Airport", "SS"],
"NBO":["Nairobi", "Jomo Kenyatta International Airport", "KE"],
"MBA":["Mombasa", "Moi International Airport", "KE"],
"TIP":["Tripoli", "Tripoli International Airport", "LY"],
"KGL":["Kigali", "Kigali International Airport", "RW"],
"KRT":["Khartoum", "Khartoum International Airport", "SD"],
"DAR":["Dar es Salaam", "Julius Nyerere International Airport", "TZ"],
"ZNZ":["Zanzibar", "Abeid Amani Karume International Airport", "TZ"],
"EBB":["Kampala", "Entebbe International Airport", "UG"],
"ATL":["Atlanta", "Hartsfield Jackson Atlanta International Airport", "US"],
"AUS":["Austin", "Austin Bergstrom International Airport", "US"],
"BNA":["Nashville", "Nashville International Airport", "US"],
"BOS":["Boston", "Logan International Airport", "US"],
"BUF":["Buffalo", "Buffalo Niagara International Airport", "US"],
"BWI":["Baltimore", "Baltimore/Washington International Thurgood Marshall Airport", "US"],
"CLE":["Cleveland", "Cleveland Hopkins International Airport", "US"],
"CLT":["Charlotte", "Charlotte Douglas International Airport", "US"],
"CMH":["Columbus", "John Glenn Columbus International Airport", "US"],
"CVG":["Cincinnati / Covington", "Cincinnati Northern Kentucky International Airport", "US"],
"DCA":["Washington", "Ronald Reagan Washington National Airport", "US"],
"DEN":["Denver", "Denver International Airport", "US"],
"DFW":["Dallas-Fort Worth", "Dallas Fort Worth International Airport", "US"],
"DTW":["Detroit", "Detroit Metropolitan Wayne County Airport", "US"],
"EWR":["New York", "Newark Liberty International Airport", "US"],
"FLL":["Fort Lauderdale", "Fort Lauderdale Hollywood International Airport", "US"],
"IAD":["Washington", "Washington Dulles International Airport", "US"],
"IAH":["Houston", "George Bush Intercontinental Houston Airport", "US"],
"IND":["Indianapolis", "Indianapolis International Airport", "US"],
"JAX":["Jacksonville", "Jacksonville International Airport", "US"],
"JFK":["New York", "John F Kennedy International Airport", "US"],
"LAS":["Las Vegas", "McCarran International Airport", "US"],
"LAX":["Los Angeles", "Los Angeles International Airport", "US"],
"LGA":["New York", "La Guardia Airport", "US"],
"MCI":["Kansas City", "Kansas City International Airport", "US"],
"MCO":["Orlando", "Orlando International Airport", "US"],
"MEM":["Memphis", "Memphis International Airport", "US"],
"MIA":["Miami", "Miami International Airport", "US"],
"MKE":["Milwaukee", "General Mitchell International Airport", "US"],
"MSY":["New Orleans", "Louis Armstrong New Orleans International Airport", "US"],
"OAK":["Oakland", "Metropolitan Oakland International Airport", "US"],
"ONT":["Ontario", "Ontario International Airport", "US"],
"ORD":["Chicago", "Chicago O'Hare International Airport", "US"],
"PBI":["West Palm Beach", "Palm Beach International Airport", "US"],
"PDX":["Portland", "Portland International Airport", "US"],
"PHL":["Philadelphia", "Philadelphia International Airport", "US"],
"PHX":["Phoenix", "Phoenix Sky Harbor International Airport", "US"],
"PIT":["Pittsburgh", "Pittsburgh International Airport", "US"],
"PVD":["Providence", "Theodore Francis Green State Airport", "US"],
"PWM":["Portland", "Portland International Jetport", "US"],
"RDU":["Raleigh/Durham", "Raleigh Durham International Airport", "US"],
"RIC":["Richmond", "Richmond International Airport", "US"],
"RNO":["Reno", "Reno Tahoe International Airport", "US"],
"RSW":["Fort Myers", "Southwest Florida International Airport", "US"],
"SAN":["San Diego", "San Diego International Airport", "US"],
"SAT":["San Antonio", "San Antonio International Airport", "US"],
"SAV":["Savannah", "Savannah Hilton Head International Airport", "US"],
"SDF":["Louisville", "Louisville Muhammad Ali International Airport", "US"],
"SEA":["Seattle", "Seattle Tacoma International Airport", "US"],
"SFB":["Orlando", "Orlando Sanford International Airport", "US"],
"SFO":["San Francisco", "San Francisco International Airport", "US"],
"SJC":["San Jose", "Norman Y. Mineta San Jose International Airport", "US"],
"SLC":["Salt Lake City", "Salt Lake City International Airport", "US"],
"SMF":["Sacramento", "Sacramento International Airport", "US"],
"STL":["St Louis", "St Louis Lambert International Airport", "US"],
"SYR":["Syracuse", "Syracuse Hancock International Airport", "US"],
"TPA":["Tampa", "Tampa International Airport", "US"],
"TUL":["Tulsa", "Tulsa International Airport", "US"],
"TIA":["Tirana", "Tirana International Airport Mother Teresa", "AL"],
"BOJ":["Burgas", "Burgas Airport", "BG"],
"SOF":["Sofia", "Sofia Airport", "BG"],
"VAR":["Varna", "Varna Airport", "BG"],
"LCA":["Larnaca", "Larnaca International Airport", "CY"],
"ZAG":["Zagreb", "Zagreb Airport", "HR"],
"BCN":["Barcelona", "Josep Tarradellas Barcelona-El Prat Airport", "ES"],
"IBZ":["Ibiza", "Ibiza Airport", "ES"],
"MAD":["Madrid", "Adolfo Suarez Madrid-Barajas Airport", "ES"],
"AGP":["Malaga", "Malaga-Costa del Sol Airport", "ES"],
"PMI":["Palma De Mallorca", "Palma de Mallorca Airport", "ES"],
"SCQ":["Santiago de Compostela", "Santiago-Rosalia de Castro Airport", "ES"],
"BOD":["Bordeaux/Merignac", "Bordeaux-Merignac Airport", "FR"],
"TLS":["Toulouse/Blagnac", "Toulouse-Blagnac Airport", "FR"],
"LYS":["Lyon", "Lyon Saint-Exupery Airport", "FR"],
"MRS":["Marseille", "Marseille Provence Airport", "FR"],
"NCE":["Nice", "Nice-Cote d'Azur Airport", "FR"],
"CDG":["Paris", "Charles de Gaulle International Airport", "FR"],
"ORY":["Paris", "Paris-Orly Airport", "FR"],
"BSL":["Bale/Mulhouse", "EuroAirport Basel-Mulhouse-Freiburg Airport", "FR"],
"ATH":["Athens", "Athens Eleftherios Venizelos International Airport", "GR"],
"HER":["Heraklion", "Heraklion International Nikos Kazantzakis Airport", "GR"],
"SKG":["Thessaloniki", "Thessaloniki Macedonia International Airport", "GR"],
"BUD":["Budapest", "Budapest Liszt Ferenc International Airport", "HU"],
"LHS":["Lake Havasu City", "Lake Havasu City International Airport", "US"],
"CTA":["Catania", "Catania-Fontanarossa Airport", "IT"],
"PMO":["Palermo", "Falcone-Borsellino Airport", "IT"],
"CAG":["Cagliari", "Cagliari Elmas Airport", "IT"],
"MXP":["Milan", "Malpensa International Airport", "IT"],
"BGY":["Milan", "Milan Bergamo Airport", "IT"],
"TRN":["Torino", "Turin Airport", "IT"],
"BLQ":["Bologna", "Bologna Guglielmo Marconi Airport", "IT"],
"VRN":["Verona", "Verona Villafranca Airport", "IT"],
"VCE":["Venice", "Venice Marco Polo Airport", "IT"],
"FCO":["Rome", "Rome-Fiumicino Leonardo da Vinci International Airport", "IT"],
"NAP":["Napoli", "Naples International Airport", "IT"],
"PSA":["Pisa", "Pisa International Airport", "IT"],
"LJU":["Ljubljana", "Ljubljana Joze Pucnik Airport", "SI"],
"PRG":["Prague", "Vaclav Havel Airport Prague", "CZ"],
"TLV":["Tel Aviv", "Ben Gurion International Airport", "IL"],
"ETM":["Eilat", "Ramon Airport", "IL"],
"MLA":["Valletta", "Malta International Airport", "MT"],
"VIE":["Vienna", "Vienna International Airport", "AT"],
"FAO":["Faro", "Faro Airport", "PT"],
"PDL":["Ponta Delgada", "Joao Paulo II Airport", "PT"],
"OPO":["Porto", "Francisco de Sa Carneiro Airport", "PT"],
"LIS":["Lisbon", "Humberto Delgado Airport (Lisbon Portela Airport)", "PT"],
"OTP":["Bucharest", "Henri Coanda International Airport", "RO"],
"GVA":["Geneva", "Geneva Cointrin International Airport", "CH"],
"ZRH":["Zurich", "Zurich Airport", "CH"],
"ESB":["Ankara", "Esenboga International Airport", "TR"],
"AYT":["Antalya", "Antalya International Airport", "TR"],
"ISL":["Bakirkoy, Istanbul", "Istanbul Ataturk Airport", "TR"],
"ADB":["Izmir", "Adnan Menderes International Airport", "TR"],
"DLM":["Dalaman", "Dalaman International Airport", "TR"],
"BJV":["Bodrum", "Milas Bodrum International Airport", "TR"],
"SAW":["Pendik, Istanbul", "Istanbul Sabiha Gokcen International Airport", "TR"],
"IST":["Arnavutkoy, Istanbul", "Istanbul Airport", "TR"],
"SKP":["Skopje", "Skopje International Airport", "MK"],
"BEG":["Belgrade", "Belgrade Nikola Tesla Airport", "RS"],
"TGD":["Podgorica", "Podgorica Airport / Podgorica Golubovci Airbase", "ME"],
"BTS":["Bratislava", "M. R. Stefanik Airport", "SK"],
"PLS":["Providenciales", "Providenciales International Airport", "TC"],
"PUJ":["Punta Cana", "Punta Cana International Airport", "DO"],
"SDQ":["Santo Domingo", "Las Americas International Airport", "DO"],
"GUA":["Guatemala City", "La Aurora Airport", "GT"],
"KIN":["Kingston", "Norman Manley International Airport", "JM"],
"ACA":["Acapulco", "General Juan N Alvarez International Airport", "MX"],
"GDL":["Guadalajara", "Don Miguel Hidalgo Y Costilla International Airport", "MX"],
"HMO":["Hermosillo", "General Ignacio P. Garcia International Airport", "MX"],
"MEX":["Mexico City", "Licenciado Benito Juarez International Airport", "MX"],
"MZT":["Mazatlan", "General Rafael Buelna International Airport", "MX"],
"PVR":["Puerto Vallarta", "Licenciado Gustavo Diaz Ordaz International Airport", "MX"],
"SJD":["San Jose del Cabo", "Los Cabos International Airport", "MX"],
"TIJ":["Tijuana", "General Abelardo L. Rodriguez International Airport", "MX"],
"CUN":["Cancun", "Cancun International Airport", "MX"],
"PTY":["Tocumen", "Tocumen International Airport", "PA"],
"LIR":["Liberia", "Guanacaste Airport", "CR"],
"SAL":["San Salvador (San Luis Talpa)", "Monsenor Oscar Arnulfo Romero International Airport", "SV"],
"PAP":["Port-au-Prince", "Toussaint Louverture International Airport", "HT"],
"HAV":["Havana", "Jose Marti International Airport", "CU"],
"VRA":["Varadero", "Juan Gualberto Gomez International Airport", "CU"],
"GCM":["Georgetown", "Owen Roberts International Airport", "KY"],
"NAS":["Nassau", "Lynden Pindling International Airport", "BS"],
"BZE":["Belize City", "Philip S. W. Goldson International Airport", "BZ"],
"RAR":["Avarua", "Rarotonga International Airport", "CK"],
"PPT":["Papeete", "Faa'a International Airport", "PF"],
"VLI":["Port Vila", "Bauerfield International Airport", "VU"],
"GEA":["Noumea", "Noumea Magenta Airport", "NC"],
"AKL":["Auckland", "Auckland International Airport", "NZ"],
"CHC":["Christchurch", "Christchurch International Airport", "NZ"],
"WLG":["Wellington", "Wellington International Airport", "NZ"],
"BAH":["Manama", "Bahrain International Airport", "BH"],
"DMM":["Ad Dammam", "King Fahd International Airport", "SA"],
"JED":["Jeddah", "King Abdulaziz International Airport", "SA"],
"MED":["Medina", "Prince Mohammad Bin Abdulaziz Airport", "SA"],
"RUH":["Riyadh", "King Khaled International Airport", "SA"],
"IKA":["Tehran", "Imam Khomeini International Airport", "IR"],
"THR":["Tehran", "Mehrabad International Airport", "IR"],
"MHD":["Mashhad", "Mashhad International Airport", "IR"],
"SYZ":["Shiraz", "Shiraz Shahid Dastghaib International Airport", "IR"],
"AMM":["Amman", "Queen Alia International Airport", "JO"],
"KWI":["Kuwait City", "Kuwait International Airport", "KW"],
"BEY":["Beirut", "Beirut Rafic Hariri International Airport", "LB"],
"DQM":["Duqm", "Duqm International Airport", "OM"],
"AUH":["Abu Dhabi", "Abu Dhabi International Airport", "AE"],
"DXB":["Dubai", "Dubai International Airport", "AE"],
"DWC":["Jebel Ali", "Al Maktoum International Airport", "AE"],
"SHJ":["Sharjah", "Sharjah International Airport", "AE"],
"MCT":["Muscat", "Muscat International Airport", "OM"],
"ISB":["Islamabad", "Islamabad International Airport", "PK"],
"KHI":["Karachi", "Jinnah International Airport", "PK"],
"BGW":["Baghdad", "Baghdad International Airport / New Al Muthana Air Base", "IQ"],
"DAM":["Damascus", "Damascus International Airport", "SY"],
"DOH":["Doha", "Hamad International Airport", "QA"],
"FAI":["Fairbanks", "Fairbanks International Airport", "US"],
"ANC":["Anchorage", "Ted Stevens Anchorage International Airport", "US"],
"GUM":["Hagatna, Guam International Airport", "Antonio B. Won Pat International Airport", "GU"],
"HNL":["Honolulu", "Daniel K Inouye International Airport", "US"],
"KHH":["Kaohsiung (Xiaogang)", "Kaohsiung International Airport", "TW"],
"TPE":["Taipei", "Taiwan Taoyuan International Airport", "TW"],
"NRT":["Tokyo", "Narita International Airport", "JP"],
"KIX":["Osaka", "Kansai International Airport", "JP"],
"CTS":["Sapporo", "New Chitose Airport", "JP"],
"FUK":["Fukuoka", "Fukuoka Airport", "JP"],
"KOJ":["Kagoshima", "Kagoshima Airport", "JP"],
"NGO":["Tokoname", "Chubu Centrair International Airport", "JP"],
"ITM":["Osaka", "Osaka International Airport", "JP"],
"SDJ":["Natori", "Sendai Airport", "JP"],
"HND":["Tokyo", "Tokyo Haneda International Airport", "JP"],
"MWX":["Piseo-ri (Muan)", "Muan International Airport", "KR"],
"CJU":["Jeju City", "Jeju International Airport", "KR"],
"PUS":["Busan", "Gimhae International Airport", "KR"],
"ICN":["Seoul", "Incheon International Airport", "KR"],
"GMP":["Seoul", "Gimpo International Airport", "KR"],
"OKA":["Naha", "Naha Airport / JASDF Naha Air Base", "JP"],
"MNL":["Manila", "Ninoy Aquino International Airport", "PH"],
"DVO":["Davao", "Francisco Bangoy International Airport", "PH"],
"CEB":["Lapu-Lapu City", "Mactan Cebu International Airport", "PH"],
"GRV":["Grozny", "Grozny North Airport", "RU"],
"AEP":["Buenos Aires", "Jorge Newbery Airpark", "AR"],
"EZE":["Buenos Aires (Ezeiza)", "Ministro Pistarini International Airport", "AR"],
"BEL":["Belem", "Val de Cans/Julio Cezar Ribeiro International Airport", "BR"],
"BSB":["Brasilia", "Presidente Juscelino Kubitschek International Airport", "BR"],
"CNF":["Belo Horizonte", "Tancredo Neves International Airport", "BR"],
"MAO":["Manaus", "Eduardo Gomes International Airport", "BR"],
"FLN":["Florianopolis", "Hercilio Luz International Airport", "BR"],
"GIG":["Rio De Janeiro", "Rio Galeao - Tom Jobim International Airport", "BR"],
"GRU":["Sao Paulo", "Guarulhos - Governador Andre Franco Montoro International Airport", "BR"],
"SSA":["Salvador", "Deputado Luiz Eduardo Magalhaes International Airport", "BR"],
"SCL":["Santiago", "Comodoro Arturo Merino Benitez International Airport", "CL"],
"GYE":["Guayaquil", "Jose Joaquin de Olmedo International Airport", "EC"],
"UIO":["Quito", "Mariscal Sucre International Airport", "EC"],
"BOG":["Bogota", "El Dorado International Airport", "CO"],
"VVI":["Santa Cruz", "Viru Viru International Airport", "BO"],
"PBM":["Zandery", "Johan Adolf Pengel International Airport", "SR"],
"CAY":["Matoury", "Cayenne - Felix Eboue Airport", "GF"],
"LIM":["Lima", "Jorge Chavez International Airport", "PE"],
"CUZ":["Cusco", "Alejandro Velasco Astete International Airport", "PE"],
"MVD":["Montevideo", "Carrasco International /General C L Berisso Airport", "UY"],
"BLA":["Barcelona", "General Jose Antonio Anzoategui International Airport", "VE"],
"CCS":["Caracas", "Simon Bolivar International Airport", "VE"],
"FDF":["Fort-de-France", "Martinique Aime Cesaire International Airport", "MQ"],
"PTP":["Pointe-a-Pitre", "Pointe-a-Pitre Le Raizet International  Airport", "GP"],
"SJU":["San Juan", "Luis Munoz Marin International Airport", "PR"],
"UVF":["Vieux Fort", "Hewanorra International Airport", "LC"],
"NBE":["Enfidha", "Enfidha - Hammamet International Airport", "TN"],
"AUA":["Oranjestad", "Queen Beatrix International Airport", "AW"],
"BON":["Kralendijk, Bonaire", "Flamingo International Airport", "BQ"],
"CUR":["Willemstad", "Hato International Airport", "CW"],
"SXM":["Saint Martin", "Princess Juliana International Airport", "SX"],
"ALA":["Almaty", "Almaty Airport", "KZ"],
"NQZ":["Nur-Sultan", "Nursultan Nazarbayev International Airport", "KZ"],
"FRU":["Bishkek", "Manas International Airport", "KG"],
"HSA":["", "Hazrat Sultan International Airport", "KZ"],
"GYD":["Baku", "Heydar Aliyev International Airport", "AZ"],
"EVN":["Yerevan", "Zvartnots International Airport", "AM"],
"TBS":["Tbilisi", "Tbilisi International Airport", "GE"],
"VVO":["Artyom", "Vladivostok International Airport", "RU"],
"KBP":["Kiev", "Boryspil International Airport", "UA"],
"LWO":["Lviv", "Lviv International Airport", "UA"],
"LED":["St. Petersburg", "Pulkovo Airport", "RU"],
"MSQ":["Minsk", "Minsk National Airport", "BY"],
"KJA":["Krasnoyarsk", "Krasnoyarsk International Airport", "RU"],
"OVB":["Novosibirsk", "Novosibirsk Tolmachevo Airport", "RU"],
"ROV":["Rostov-on-Don", "Platov International Airport", "RU"],
"AER":["Sochi", "Sochi International Airport", "RU"],
"SVX":["Yekaterinburg", "Koltsovo Airport", "RU"],
"ASB":["Ashgabat", "Ashgabat International Airport", "TM"],
"TAS":["Tashkent", "Tashkent International Airport", "UZ"],
"ZIA":["Moscow", "Zhukovsky International Airport", "RU"],
"DME":["Moscow", "Domodedovo International Airport", "RU"],
"SVO":["Moscow", "Sheremetyevo International Airport", "RU"],
"VKO":["Moscow", "Vnukovo International Airport", "RU"],
"KZN":["Kazan", "Kazan International Airport", "RU"],
"GSV":["Saratov", "Gagarin International Airport", "RU"],
"UFA":["Ufa", "Ufa International Airport", "RU"],
"KUF":["Samara", "Kurumoch International Airport", "RU"],
"BOM":["Mumbai", "Chhatrapati Shivaji International Airport", "IN"],
"GOI":["Vasco da Gama", "Dabolim Airport", "IN"],
"CMB":["Colombo", "Bandaranaike International Colombo Airport", "LK"],
"HRI":["", "Mattala Rajapaksa International Airport", "LK"],
"PNH":["Phnom Penh (Pou Senchey)", "Phnom Penh International Airport", "KH"],
"REP":["Siem Reap", "Siem Reap International Airport", "KH"],
"CCU":["Kolkata", "Netaji Subhash Chandra Bose International Airport", "IN"],
"DAC":["Dhaka", "Hazrat Shahjalal International Airport", "BD"],
"HKG":["Hong Kong", "Hong Kong International Airport", "HK"],
"DEL":["New Delhi", "Indira Gandhi International Airport", "IN"],
"MFM":["Freguesia de Nossa Senhora do Carmo (Taipa)", "Macau International Airport", "MO"],
"KTM":["Kathmandu", "Tribhuvan International Airport", "NP"],
"BLR":["Bangalore", "Kempegowda International Airport", "IN"],
"COK":["Kochi", "Cochin International Airport", "IN"],
"HYD":["Hyderabad", "Rajiv Gandhi International Airport", "IN"],
"MAA":["Chennai", "Chennai International Airport", "IN"],
"TRV":["Thiruvananthapuram", "Trivandrum International Airport", "IN"],
"MLE":["Male", "Male International Airport", "MV"],
"DMK":["Bangkok", "Don Mueang International Airport", "TH"],
"BKK":["Bangkok", "Suvarnabhumi Airport", "TH"],
"CNX":["Chiang Mai", "Chiang Mai International Airport", "TH"],
"HKT":["Phuket", "Phuket International Airport", "TH"],
"HAN":["Soc Son, Hanoi", "Noi Bai International Airport", "VN"],
"SGN":["Ho Chi Minh City", "Tan Son Nhat International Airport", "VN"],
"MDL":["Mandalay", "Mandalay International Airport", "MM"],
"RGN":["Yangon", "Yangon International Airport", "MM"],
"UPG":["Ujung Pandang-Celebes Island", "Hasanuddin International Airport", "ID"],
"DPS":["Denpasar-Bali Island", "Ngurah Rai (Bali) International Airport", "ID"],
"SUB":["Surabaya", "Juanda International Airport", "ID"],
"BWN":["Bandar Seri Begawan", "Brunei International Airport", "BN"],
"CGK":["Jakarta", "Soekarno-Hatta International Airport", "ID"],
"KUL":["Kuala Lumpur", "Kuala Lumpur International Airport", "MY"],
"SIN":["Singapore", "Singapore Changi Airport", "SG"],
"BNE":["Brisbane", "Brisbane International Airport", "AU"],
"MEL":["Melbourne", "Melbourne International Airport", "AU"],
"YNT":["Yantai", "Yantai Penglai International Airport", "CN"],
"ADL":["Adelaide", "Adelaide International Airport", "AU"],
"PER":["Perth", "Perth International Airport", "AU"],
"SYD":["Sydney", "Sydney Kingsford Smith International Airport", "AU"],
"PEK":["Beijing", "Beijing Capital International Airport", "CN"],
"PKX":["Beijing", "Beijing Daxing International Airport", "CN"],
"HET":["Hohhot", "Baita International Airport", "CN"],
"TSN":["Tianjin", "Tianjin Binhai International Airport", "CN"],
"TYN":["Taiyuan", "Taiyuan Wusu Airport", "CN"],
"CAN":["Guangzhou (Huadu)", "Guangzhou Baiyun International Airport", "CN"],
"CSX":["Changsha", "Changsha Huanghua International Airport", "CN"],
"KWL":["Guilin (Lingui)", "Guilin Liangjiang International Airport", "CN"],
"NNG":["Nanning (Jiangnan)", "Nanning Wuxu Airport", "CN"],
"SZX":["Shenzhen (Bao'an)", "Shenzhen Bao'an International Airport", "CN"],
"CGO":["Zhengzhou", "Zhengzhou Xinzheng International Airport", "CN"],
"WUH":["Wuhan", "Wuhan Tianhe International Airport", "CN"],
"HAK":["Haikou (Meilan)", "Haikou Meilan International Airport", "CN"],
"SYX":["Sanya (Tianya)", "Sanya Phoenix International Airport", "CN"],
"XIY":["Xi'an", "Xi'an Xianyang International Airport", "CN"],
"UBN":["Ulaanbaatar (Sergelen)", "Ulaanbaatar Chinggis Khaan International Airport", "MN"],
"KMG":["Kunming", "Kunming Changshui International Airport", "CN"],
"XMN":["Xiamen", "Xiamen Gaoqi International Airport", "CN"],
"FOC":["Fuzhou", "Fuzhou Changle International Airport", "CN"],
"HGH":["Hangzhou", "Hangzhou Xiaoshan International Airport", "CN"],
"TNA":["Jinan", "Jinan Yaoqiang International Airport", "CN"],
"NGB":["Ningbo", "Ningbo Lishe International Airport", "CN"],
"NKG":["Nanjing", "Nanjing Lukou International Airport", "CN"],
"PVG":["Shanghai (Pudong)", "Shanghai Pudong International Airport", "CN"],
"SHA":["Shanghai (Minhang)", "Shanghai Hongqiao International Airport", "CN"],
"WNZ":["Wenzhou", "Wenzhou Longwan International Airport", "CN"],
"CKG":["Chongqing", "Chongqing Jiangbei International Airport", "CN"],
"KWE":["Guiyang", "Longdongbao Airport", "CN"],
"CTU":["Chengdu", "Chengdu Shuangliu International Airport", "CN"],
"URC":["Urumqi", "Urumqi Diwopu International Airport", "CN"],
"HRB":["Harbin", "Harbin Taiping International Airport", "CN"],
"DLC":["Ganjingzi, Dalian", "Dalian Zhoushuizi International Airport", "CN"],
"SHE":["Hunnan, Shenyang", "Shenyang Taoxian International Airport", "CN"]
}

two_letter = [
    {"name": "Afghanistan", "code": "AF"},
    {"name": "Åland Islands", "code": "AX"},
    {"name": "Albania", "code": "AL"},
    {"name": "Algeria", "code": "DZ"},
    {"name": "American Samoa", "code": "AS"},
    {"name": "AndorrA", "code": "AD"},
    {"name": "Angola", "code": "AO"},
    {"name": "Anguilla", "code": "AI"},
    {"name": "Antarctica", "code": "AQ"},
    {"name": "Antigua and Barbuda", "code": "AG"},
    {"name": "Argentina", "code": "AR"},
    {"name": "Armenia", "code": "AM"},
    {"name": "Aruba", "code": "AW"},
    {"name": "Australia", "code": "AU"},
    {"name": "Austria", "code": "AT"},
    {"name": "Azerbaijan", "code": "AZ"},
    {"name": "Bahamas", "code": "BS"},
    {"name": "Bahrain", "code": "BH"},
    {"name": "Bangladesh", "code": "BD"},
    {"name": "Barbados", "code": "BB"},
    {"name": "Belarus", "code": "BY"},
    {"name": "Belgium", "code": "BE"},
    {"name": "Belize", "code": "BZ"},
    {"name": "Benin", "code": "BJ"},
    {"name": "Bermuda", "code": "BM"},
    {"name": "Bhutan", "code": "BT"},
    {"name": "Bolivia", "code": "BO"},
    {"name": "Bosnia and Herzegovina", "code": "BA"},
    {"name": "Botswana", "code": "BW"},
    {"name": "Bouvet Island", "code": "BV"},
    {"name": "Brazil", "code": "BR"},
    {"name": "British Indian Ocean Territory", "code": "IO"},
    {"name": "Brunei Darussalam", "code": "BN"},
    {"name": "Bulgaria", "code": "BG"},
    {"name": "Burkina Faso", "code": "BF"},
    {"name": "Burundi", "code": "BI"},
    {"name": "Cambodia", "code": "KH"},
    {"name": "Cameroon", "code": "CM"},
    {"name": "Canada", "code": "CA"},
    {"name": "Cape Verde", "code": "CV"},
    {"name": "Cayman Islands", "code": "KY"},
    {"name": "Central African Republic", "code": "CF"},
    {"name": "Chad", "code": "TD"},
    {"name": "Chile", "code": "CL"},
    {"name": "China", "code": "CN"},
    {"name": "Christmas Island", "code": "CX"},
    {"name": "Cocos (Keeling) Islands", "code": "CC"},
    {"name": "Colombia", "code": "CO"},
    {"name": "Comoros", "code": "KM"},
    {"name": "Congo", "code": "CG"},
    {"name": "Congo, The Democratic Republic of the", "code": "CD"},
    {"name": "Cook Islands", "code": "CK"},
    {"name": "Costa Rica", "code": "CR"},
    {"name": "Cote D\"Ivoire", "code": "CI"},
    {"name": "Croatia", "code": "HR"},
    {"name": "Cuba", "code": "CU"},
    {"name": "Cyprus", "code": "CY"},
    {"name": "Czech Republic", "code": "CZ"},
    {"name": "Denmark", "code": "DK"},
    {"name": "Djibouti", "code": "DJ"},
    {"name": "Dominica", "code": "DM"},
    {"name": "Dominican Republic", "code": "DO"},
    {"name": "Ecuador", "code": "EC"},
    {"name": "Egypt", "code": "EG"},
    {"name": "El Salvador", "code": "SV"},
    {"name": "Equatorial Guinea", "code": "GQ"},
    {"name": "Eritrea", "code": "ER"},
    {"name": "Estonia", "code": "EE"},
    {"name": "Ethiopia", "code": "ET"},
    {"name": "Falkland Islands (Malvinas)", "code": "FK"},
    {"name": "Faroe Islands", "code": "FO"},
    {"name": "Fiji", "code": "FJ"},
    {"name": "Finland", "code": "FI"},
    {"name": "France", "code": "FR"},
    {"name": "French Guiana", "code": "GF"},
    {"name": "French Polynesia", "code": "PF"},
    {"name": "French Southern Territories", "code": "TF"},
    {"name": "Gabon", "code": "GA"},
    {"name": "Gambia", "code": "GM"},
    {"name": "Georgia", "code": "GE"},
    {"name": "Germany", "code": "DE"},
    {"name": "Ghana", "code": "GH"},
    {"name": "Gibraltar", "code": "GI"},
    {"name": "Greece", "code": "GR"},
    {"name": "Greenland", "code": "GL"},
    {"name": "Grenada", "code": "GD"},
    {"name": "Guadeloupe", "code": "GP"},
    {"name": "Guam", "code": "GU"},
    {"name": "Guatemala", "code": "GT"},
    {"name": "Guernsey", "code": "GG"},
    {"name": "Guinea", "code": "GN"},
    {"name": "Guinea-Bissau", "code": "GW"},
    {"name": "Guyana", "code": "GY"},
    {"name": "Haiti", "code": "HT"},
    {"name": "Heard Island and Mcdonald Islands", "code": "HM"},
    {"name": "Holy See (Vatican City State)", "code": "VA"},
    {"name": "Honduras", "code": "HN"},
    {"name": "Hong Kong", "code": "HK"},
    {"name": "Hungary", "code": "HU"},
    {"name": "Iceland", "code": "IS"},
    {"name": "India", "code": "IN"},
    {"name": "Indonesia", "code": "ID"},
    {"name": "Iran, Islamic Republic Of", "code": "IR"},
    {"name": "Iraq", "code": "IQ"},
    {"name": "Ireland", "code": "IE"},
    {"name": "Isle of Man", "code": "IM"},
    {"name": "Israel", "code": "IL"},
    {"name": "Italy", "code": "IT"},
    {"name": "Jamaica", "code": "JM"},
    {"name": "Japan", "code": "JP"},
    {"name": "Jersey", "code": "JE"},
    {"name": "Jordan", "code": "JO"},
    {"name": "Kazakhstan", "code": "KZ"},
    {"name": "Kenya", "code": "KE"},
    {"name": "Kiribati", "code": "KI"},
    {"name": "Korea, Democratic People\"S Republic of", "code": "KP"},
    {"name": "Korea, Republic of", "code": "KR"},
    {"name": "Kuwait", "code": "KW"},
    {"name": "Kyrgyzstan", "code": "KG"},
    {"name": "Lao People\"S Democratic Republic", "code": "LA"},
    {"name": "Latvia", "code": "LV"},
    {"name": "Lebanon", "code": "LB"},
    {"name": "Lesotho", "code": "LS"},
    {"name": "Liberia", "code": "LR"},
    {"name": "Libyan Arab Jamahiriya", "code": "LY"},
    {"name": "Liechtenstein", "code": "LI"},
    {"name": "Lithuania", "code": "LT"},
    {"name": "Luxembourg", "code": "LU"},
    {"name": "Macao", "code": "MO"},
    {"name": "Macedonia, The Former Yugoslav Republic of", "code": "MK"},
    {"name": "Madagascar", "code": "MG"},
    {"name": "Malawi", "code": "MW"},
    {"name": "Malaysia", "code": "MY"},
    {"name": "Maldives", "code": "MV"},
    {"name": "Mali", "code": "ML"},
    {"name": "Malta", "code": "MT"},
    {"name": "Marshall Islands", "code": "MH"},
    {"name": "Martinique", "code": "MQ"},
    {"name": "Mauritania", "code": "MR"},
    {"name": "Mauritius", "code": "MU"},
    {"name": "Mayotte", "code": "YT"},
    {"name": "Mexico", "code": "MX"},
    {"name": "Micronesia, Federated States of", "code": "FM"},
    {"name": "Moldova, Republic of", "code": "MD"},
    {"name": "Monaco", "code": "MC"},
    {"name": "Mongolia", "code": "MN"},
    {"name": "Montserrat", "code": "MS"},
    {"name": "Morocco", "code": "MA"},
    {"name": "Mozambique", "code": "MZ"},
    {"name": "Myanmar", "code": "MM"},
    {"name": "Namibia", "code": "NA"},
    {"name": "Nauru", "code": "NR"},
    {"name": "Nepal", "code": "NP"},
    {"name": "Netherlands", "code": "NL"},
    {"name": "Netherlands Antilles", "code": "AN"},
    {"name": "New Caledonia", "code": "NC"},
    {"name": "New Zealand", "code": "NZ"},
    {"name": "Nicaragua", "code": "NI"},
    {"name": "Niger", "code": "NE"},
    {"name": "Nigeria", "code": "NG"},
    {"name": "Niue", "code": "NU"},
    {"name": "Norfolk Island", "code": "NF"},
    {"name": "Northern Mariana Islands", "code": "MP"},
    {"name": "Norway", "code": "NO"},
    {"name": "Oman", "code": "OM"},
    {"name": "Pakistan", "code": "PK"},
    {"name": "Palau", "code": "PW"},
    {"name": "Palestinian Territory, Occupied", "code": "PS"},
    {"name": "Panama", "code": "PA"},
    {"name": "Papua New Guinea", "code": "PG"},
    {"name": "Paraguay", "code": "PY"},
    {"name": "Peru", "code": "PE"},
    {"name": "Philippines", "code": "PH"},
    {"name": "Pitcairn", "code": "PN"},
    {"name": "Poland", "code": "PL"},
    {"name": "Portugal", "code": "PT"},
    {"name": "Puerto Rico", "code": "PR"},
    {"name": "Qatar", "code": "QA"},
    {"name": "Reunion", "code": "RE"},
    {"name": "Romania", "code": "RO"},
    {"name": "Russian Federation", "code": "RU"},
    {"name": "RWANDA", "code": "RW"},
    {"name": "Saint Helena", "code": "SH"},
    {"name": "Saint Kitts and Nevis", "code": "KN"},
    {"name": "Saint Lucia", "code": "LC"},
    {"name": "Saint Pierre and Miquelon", "code": "PM"},
    {"name": "Saint Vincent and the Grenadines", "code": "VC"},
    {"name": "Samoa", "code": "WS"},
    {"name": "San Marino", "code": "SM"},
    {"name": "Sao Tome and Principe", "code": "ST"},
    {"name": "Saudi Arabia", "code": "SA"},
    {"name": "Senegal", "code": "SN"},
    {"name": "Serbia and Montenegro", "code": "CS"},
    {"name": "Seychelles", "code": "SC"},
    {"name": "Sierra Leone", "code": "SL"},
    {"name": "Singapore", "code": "SG"},
    {"name": "Slovakia", "code": "SK"},
    {"name": "Slovenia", "code": "SI"},
    {"name": "Solomon Islands", "code": "SB"},
    {"name": "Somalia", "code": "SO"},
    {"name": "South Africa", "code": "ZA"},
    {"name": "South Georgia and the South Sandwich Islands", "code": "GS"},
    {"name": "Spain", "code": "ES"},
    {"name": "Sri Lanka", "code": "LK"},
    {"name": "Sudan", "code": "SD"},
    {"name": "Suriname", "code": "SR"},
    {"name": "Svalbard and Jan Mayen", "code": "SJ"},
    {"name": "Swaziland", "code": "SZ"},
    {"name": "Sweden", "code": "SE"},
    {"name": "Switzerland", "code": "CH"},
    {"name": "Syrian Arab Republic", "code": "SY"},
    {"name": "Taiwan, Province of China", "code": "TW"},
    {"name": "Tajikistan", "code": "TJ"},
    {"name": "Tanzania, United Republic of", "code": "TZ"},
    {"name": "Thailand", "code": "TH"},
    {"name": "Timor-Leste", "code": "TL"},
    {"name": "Togo", "code": "TG"},
    {"name": "Tokelau", "code": "TK"},
    {"name": "Tonga", "code": "TO"},
    {"name": "Trinidad and Tobago", "code": "TT"},
    {"name": "Tunisia", "code": "TN"},
    {"name": "Turkey", "code": "TR"},
    {"name": "Turkmenistan", "code": "TM"},
    {"name": "Turks and Caicos Islands", "code": "TC"},
    {"name": "Tuvalu", "code": "TV"},
    {"name": "Uganda", "code": "UG"},
    {"name": "Ukraine", "code": "UA"},
    {"name": "United Arab Emirates", "code": "AE"},
    {"name": "United Kingdom", "code": "GB"},
    {"name": "United States", "code": "US"},
    {"name": "United States Minor Outlying Islands", "code": "UM"},
    {"name": "Uruguay", "code": "UY"},
    {"name": "Uzbekistan", "code": "UZ"},
    {"name": "Vanuatu", "code": "VU"},
    {"name": "Venezuela", "code": "VE"},
    {"name": "Viet Nam", "code": "VN"},
    {"name": "Virgin Islands, British", "code": "VG"},
    {"name": "Virgin Islands, U.S.", "code": "VI"},
    {"name": "Wallis and Futuna", "code": "WF"},
    {"name": "Western Sahara", "code": "EH"},
    {"name": "Yemen", "code": "YE"},
    {"name": "Zambia", "code": "ZM"},
    {"name": "Zimbabwe", "code": "ZW"}
]

for key, value in airport_list.items():
        for j in two_letter:
            print(j["code"])
            print(value[-1])
            if j["code"] == (value[-1]):
                airport_list[key][-1] = j["name"]
                print(j["name"])
                print(airport_list[key][-1])

with open("final_airport_list", "w") as f:
    f.write(str(airport_list))


