airport_list ={
'HIR': ['Honiara', 'Honiara International Airport', 'Solomon Islands'],
 'POM': ['Port Moresby', 'Port Moresby Jacksons International Airport', 'Papua New Guinea'],
 'KEF': ['Reykjavik', 'Keflavik International Airport', 'Iceland'],
 'YEG': ['Edmonton', 'Edmonton International Airport', 'Canada'],
 'YHZ': ['Halifax', 'Halifax / Stanfield International Airport', 'Canada'],
 'YLW': ['Kelowna', 'Kelowna International Airport', 'Canada'],
 'YOW': ['Ottawa', 'Ottawa Macdonald-Cartier International Airport', 'Canada'],
 'YQB': ['Quebec', 'Quebec Jean Lesage International Airport', 'Canada'],
 'YUL': ['Montreal', 'Montreal / Pierre Elliott Trudeau International Airport', 'Canada'],
 'YVR': ['Vancouver', 'Vancouver International Airport', 'Canada'],
 'YWG': ['Winnipeg', 'Winnipeg / James Armstrong Richardson International Airport', 'Canada'],
 'YYC': ['Calgary', 'Calgary International Airport', 'Canada'],
 'YYT': ["St. John's", "St. John's International Airport", 'Canada'],
 'YYZ': ['Toronto', 'Lester B. Pearson International Airport', 'Canada'],
 'ALG': ['Algiers', 'Houari Boumediene Airport', 'Algeria'],
 'ACC': ['Accra', 'Kotoka International Airport', 'Ghana'],
 'ABV': ['Abuja', 'Nnamdi Azikiwe International Airport', 'Nigeria'],
 'LOS': ['Lagos', 'Murtala Muhammed International Airport', 'Nigeria'],
 'NIM': ['Niamey', 'Diori Hamani International Airport', 'Niger'],
 'TUN': ['Tunis', 'Tunis Carthage International Airport', 'Tunisia'],
 'BRU': ['Brussels', 'Brussels Airport', 'Belgium'],
 'BER': ['Berlin', 'Berlin Brandenburg Airport', 'Germany'],
 'FRA': ['Frankfurt am Main', 'Frankfurt am Main Airport', 'Germany'],
 'HAM': ['Hamburg', 'Hamburg Helmut Schmidt Airport', 'Germany'],
 'CGN': ['Cologne', 'Cologne Bonn Airport', 'Germany'],
 'DUS': ['Dusseldorf', 'Dusseldorf Airport', 'Germany'],
 'MUC': ['Munich', 'Munich Airport', 'Germany'],
 'NUE': ['Nuremberg', 'Nuremberg Airport', 'Germany'],
 'LEJ': ['Leipzig', 'Leipzig/Halle Airport', 'Germany'],
 'STR': ['Stuttgart', 'Stuttgart Airport', 'Germany'],
 'HAJ': ['Hannover', 'Hannover Airport', 'Germany'],
 'TLL': ['Tallinn', 'Lennart Meri Tallinn Airport', 'Estonia'],
 'HEL': ['Helsinki', 'Helsinki Vantaa Airport', 'Finland'],
 'BFS': ['Belfast', 'Belfast International Airport', 'United Kingdom'],
 'BHX': ['Birmingham', 'Birmingham International Airport', 'United Kingdom'],
 'MAN': ['Manchester', 'Manchester Airport', 'United Kingdom'],
 'LTN': ['London', 'London Luton Airport', 'United Kingdom'],
 'LGW': ['London', 'London Gatwick Airport', 'United Kingdom'],
 'LHR': ['London', 'London Heathrow Airport', 'United Kingdom'],
 'GLA': ['Paisley, Renfrewshire', 'Glasgow International Airport', 'United Kingdom'],
 'EDI': ['Edinburgh', 'Edinburgh Airport', 'United Kingdom'],
 'STN': ['London', 'London Stansted Airport', 'United Kingdom'],
 'AMS': ['Amsterdam', 'Amsterdam Airport Schiphol', 'Netherlands'],
 'EIN': ['Eindhoven', 'Eindhoven Airport', 'Netherlands'],
 'DUB': ['Dublin', 'Dublin Airport', 'Ireland'],
 'SNN': ['Shannon', 'Shannon Airport', 'Ireland'],
 'BLL': ['Billund', 'Billund Airport', 'Denmark'],
 'CPH': ['Copenhagen', 'Copenhagen Kastrup Airport', 'Denmark'],
 'LUX': ['Luxembourg', 'Luxembourg-Findel International Airport', 'Luxembourg'],
 'BGO': ['Bergen', 'Bergen Airport, Flesland', 'Norway'],
 'OSL': ['Oslo', 'Oslo Airport, Gardermoen', 'Norway'],
 'TOS': ['Tromso', 'Tromso Airport, Langnes', 'Norway'],
 'SVG': ['Stavanger', 'Stavanger Airport, Sola', 'Norway'],
 'GDN': ['Gdansk', 'Gdansk Lech Walesa Airport', 'Poland'],
 'KRK': ['Krakow', 'Krakow John Paul II International Airport', 'Poland'],
 'WAW': ['Warsaw', 'Warsaw Chopin Airport', 'Poland'],
 'GOT': ['Gothenburg', 'Gothenburg-Landvetter Airport', 'Sweden'],
 'ARN': ['Stockholm', 'Stockholm-Arlanda Airport', 'Sweden'],
 'RIX': ['Riga', 'Riga International Airport', 'Latvia'],
 'VNO': ['Vilnius', 'Vilnius International Airport', 'Lithuania'],
 'CPT': ['Cape Town', 'Cape Town International Airport', 'South Africa'],
 'DUR': ['Durban', 'King Shaka International Airport', 'South Africa'],
 'JNB': ['Johannesburg', 'OR Tambo International Airport', 'South Africa'],
 'GBE': ['Gaborone', 'Sir Seretse Khama International Airport', 'Botswana'],
 'SHO': ['Mpaka', 'King Mswati III International Airport', 'Swaziland'],
 'MRU': ['Plaine Magnein', 'Sir Seewoosagur Ramgoolam International Airport', 'Mauritius'],
 'LUN': ['Lusaka', 'Kenneth Kaunda International Airport', 'Zambia'],
 'RUN': ['St Denis', 'Roland Garros Airport', 'Reunion'],
 'TNR': ['Antananarivo', 'Ivato Airport', 'Madagascar'],
 'LAD': ['Luanda', 'Quatro de Fevereiro Airport', 'Angola'],
 'MPM': ['Maputo', 'Maputo Airport', 'Mozambique'],
 'SEZ': ['Mahe Island', 'Seychelles International Airport', 'Seychelles'],
 'NDJ': ["N'Djamena", "N'Djamena International Airport", 'Chad'],
 'HRE': ['Harare', 'Robert Gabriel Mugabe International Airport', 'Zimbabwe'],
 'WDH': ['Windhoek', 'Hosea Kutako International Airport', 'Namibia'],
 'FIH': ['Kinshasa', 'Ndjili International Airport', 'Congo, The Democratic Republic of the'],
 'BKO': ['Bamako', 'Modibo Keita International Airport', 'Mali'],
 'BJL': ['Banjul', 'Banjul International Airport', 'Gambia'],
 'FUE': ['Fuerteventura Island', 'Fuerteventura Airport', 'Spain'],
 'LPA': ['Gran Canaria Island', 'Gran Canaria Airport', 'Spain'],
 'TFS': ['Tenerife', 'Tenerife Sur Airport', 'Spain'],
 'FNA': ['Freetown (Lungi-Town)', 'Lungi International Airport', 'Sierra Leone'],
 'ROB': ['Monrovia', 'Roberts International Airport', 'Liberia'],
 'CMN': ['Casablanca', 'Mohammed V International Airport', 'Morocco'],
 'DSS': ['Dakar', 'Blaise Diagne International Airport', 'Senegal'],
 'ADD': ['Addis Ababa', 'Addis Ababa Bole International Airport', 'Ethiopia'],
 'JIB': ['Djibouti City', 'Djibouti-Ambouli Airport', 'Djibouti'],
 'CAI': ['Cairo', 'Cairo International Airport', 'Egypt'],
 'HRG': ['Hurghada', 'Hurghada International Airport', 'Egypt'],
 'SSH': ['Sharm el-Sheikh', 'Sharm El Sheikh International Airport', 'Egypt'],
 'JUB': ['Juba', 'Juba International Airport', 'SS'],
 'NBO': ['Nairobi', 'Jomo Kenyatta International Airport', 'Kenya'],
 'MBA': ['Mombasa', 'Moi International Airport', 'Kenya'],
 'TIP': ['Tripoli', 'Tripoli International Airport', 'Libyan Arab Jamahiriya'],
 'KGL': ['Kigali', 'Kigali International Airport', 'RWANDA'],
 'KRT': ['Khartoum', 'Khartoum International Airport', 'Sudan'],
 'DAR': ['Dar es Salaam', 'Julius Nyerere International Airport', 'Tanzania, United Republic of'],
 'ZNZ': ['Zanzibar', 'Abeid Amani Karume International Airport', 'Tanzania, United Republic of'],
 'EBB': ['Kampala', 'Entebbe International Airport', 'Uganda'],
 'ATL': ['Atlanta', 'Hartsfield Jackson Atlanta International Airport', 'United States'],
 'AUS': ['Austin', 'Austin Bergstrom International Airport', 'United States'],
 'BNA': ['Nashville', 'Nashville International Airport', 'United States'],
 'BOS': ['Boston', 'Logan International Airport', 'United States'],
 'BUF': ['Buffalo', 'Buffalo Niagara International Airport', 'United States'],
 'BWI': ['Baltimore', 'Baltimore/Washington International Thurgood Marshall Airport', 'United States'],
 'CLE': ['Cleveland', 'Cleveland Hopkins International Airport', 'United States'],
 'CLT': ['Charlotte', 'Charlotte Douglas International Airport', 'United States'],
 'CMH': ['Columbus', 'John Glenn Columbus International Airport', 'United States'],
 'CVG': ['Cincinnati / Covington', 'Cincinnati Northern Kentucky International Airport', 'United States'],
 'DCA': ['Washington', 'Ronald Reagan Washington National Airport', 'United States'],
 'DEN': ['Denver', 'Denver International Airport', 'United States'],
 'DFW': ['Dallas-Fort Worth', 'Dallas Fort Worth International Airport', 'United States'],
 'DTW': ['Detroit', 'Detroit Metropolitan Wayne County Airport', 'United States'],
 'EWR': ['New York', 'Newark Liberty International Airport', 'United States'],
 'FLL': ['Fort Lauderdale', 'Fort Lauderdale Hollywood International Airport', 'United States'],
 'IAD': ['Washington', 'Washington Dulles International Airport', 'United States'],
 'IAH': ['Houston', 'George Bush Intercontinental Houston Airport', 'United States'],
 'IND': ['Indianapolis', 'Indianapolis International Airport', 'United States'],
 'JAX': ['Jacksonville', 'Jacksonville International Airport', 'United States'],
 'JFK': ['New York', 'John F Kennedy International Airport', 'United States'],
 'LAS': ['Las Vegas', 'McCarran International Airport', 'United States'],
 'LAX': ['Los Angeles', 'Los Angeles International Airport', 'United States'],
 'LGA': ['New York', 'La Guardia Airport', 'United States'],
 'MCI': ['Kansas City', 'Kansas City International Airport', 'United States'],
 'MCO': ['Orlando', 'Orlando International Airport', 'United States'],
 'MEM': ['Memphis', 'Memphis International Airport', 'United States'],
 'MIA': ['Miami', 'Miami International Airport', 'United States'],
 'MKE': ['Milwaukee', 'General Mitchell International Airport', 'United States'],
 'MSY': ['New Orleans', 'Louis Armstrong New Orleans International Airport', 'United States'],
 'OAK': ['Oakland', 'Metropolitan Oakland International Airport', 'United States'],
 'ONT': ['Ontario', 'Ontario International Airport', 'United States'],
 'ORD': ['Chicago', "Chicago O'Hare International Airport", 'United States'],
 'PBI': ['West Palm Beach', 'Palm Beach International Airport', 'United States'],
 'PDX': ['Portland', 'Portland International Airport', 'United States'],
 'PHL': ['Philadelphia', 'Philadelphia International Airport', 'United States'],
 'PHX': ['Phoenix', 'Phoenix Sky Harbor International Airport', 'United States'],
 'PIT': ['Pittsburgh', 'Pittsburgh International Airport', 'United States'],
 'PVD': ['Providence', 'Theodore Francis Green State Airport', 'United States'],
 'PWM': ['Portland', 'Portland International Jetport', 'United States'],
 'RDU': ['Raleigh/Durham', 'Raleigh Durham International Airport', 'United States'],
 'RIC': ['Richmond', 'Richmond International Airport', 'United States'],
 'RNO': ['Reno', 'Reno Tahoe International Airport', 'United States'],
 'RSW': ['Fort Myers', 'Southwest Florida International Airport', 'United States'],
 'SAN': ['San Diego', 'San Diego International Airport', 'United States'],
 'SAT': ['San Antonio', 'San Antonio International Airport', 'United States'],
 'SAV': ['Savannah', 'Savannah Hilton Head International Airport', 'United States'],
 'SDF': ['Louisville', 'Louisville Muhammad Ali International Airport', 'United States'],
 'SEA': ['Seattle', 'Seattle Tacoma International Airport', 'United States'],
 'SFB': ['Orlando', 'Orlando Sanford International Airport', 'United States'],
 'SFO': ['San Francisco', 'San Francisco International Airport', 'United States'],
 'SJC': ['San Jose', 'Norman Y. Mineta San Jose International Airport', 'United States'],
 'SLC': ['Salt Lake City', 'Salt Lake City International Airport', 'United States'],
 'SMF': ['Sacramento', 'Sacramento International Airport', 'United States'],
 'STL': ['St Louis', 'St Louis Lambert International Airport', 'United States'],
 'SYR': ['Syracuse', 'Syracuse Hancock International Airport', 'United States'],
 'TPA': ['Tampa', 'Tampa International Airport', 'United States'],
 'TUL': ['Tulsa', 'Tulsa International Airport', 'United States'],
 'TIA': ['Tirana', 'Tirana International Airport Mother Teresa', 'Albania'],
 'BOJ': ['Burgas', 'Burgas Airport', 'Bulgaria'],
 'SOF': ['Sofia', 'Sofia Airport', 'Bulgaria'],
 'VAR': ['Varna', 'Varna Airport', 'Bulgaria'],
 'LCA': ['Larnaca', 'Larnaca International Airport', 'Cyprus'],
 'ZAG': ['Zagreb', 'Zagreb Airport', 'Croatia'],
 'BCN': ['Barcelona', 'Josep Tarradellas Barcelona-El Prat Airport', 'Spain'],
 'IBZ': ['Ibiza', 'Ibiza Airport', 'Spain'],
 'MAD': ['Madrid', 'Adolfo Suarez Madrid-Barajas Airport', 'Spain'],
 'AGP': ['Malaga', 'Malaga-Costa del Sol Airport', 'Spain'],
 'PMI': ['Palma De Mallorca', 'Palma de Mallorca Airport', 'Spain'],
 'SCQ': ['Santiago de Compostela', 'Santiago-Rosalia de Castro Airport', 'Spain'],
 'BOD': ['Bordeaux/Merignac', 'Bordeaux-Merignac Airport', 'France'],
 'TLS': ['Toulouse/Blagnac', 'Toulouse-Blagnac Airport', 'France'],
 'LYS': ['Lyon', 'Lyon Saint-Exupery Airport', 'France'],
 'MRS': ['Marseille', 'Marseille Provence Airport', 'France'],
 'NCE': ['Nice', "Nice-Cote d'Azur Airport", 'France'],
 'CDG': ['Paris', 'Charles de Gaulle International Airport', 'France'],
 'ORY': ['Paris', 'Paris-Orly Airport', 'France'],
 'BSL': ['Bale/Mulhouse', 'EuroAirport Basel-Mulhouse-Freiburg Airport', 'France'],
 'ATH': ['Athens', 'Athens Eleftherios Venizelos International Airport', 'Greece'],
 'HER': ['Heraklion', 'Heraklion International Nikos Kazantzakis Airport', 'Greece'],
 'SKG': ['Thessaloniki', 'Thessaloniki Macedonia International Airport', 'Greece'],
 'BUD': ['Budapest', 'Budapest Liszt Ferenc International Airport', 'Hungary'],
 'LHS': ['Lake Havasu City', 'Lake Havasu City International Airport', 'United States'],
 'CTA': ['Catania', 'Catania-Fontanarossa Airport', 'Italy'],
 'PMO': ['Palermo', 'Falcone-Borsellino Airport', 'Italy'],
 'CAG': ['Cagliari', 'Cagliari Elmas Airport', 'Italy'],
 'MXP': ['Milan', 'Malpensa International Airport', 'Italy'],
 'BGY': ['Milan', 'Milan Bergamo Airport', 'Italy'],
 'TRN': ['Torino', 'Turin Airport', 'Italy'],
 'BLQ': ['Bologna', 'Bologna Guglielmo Marconi Airport', 'Italy'],
 'VRN': ['Verona', 'Verona Villafranca Airport', 'Italy'],
 'VCE': ['Venice', 'Venice Marco Polo Airport', 'Italy'],
 'FCO': ['Rome', 'Rome-Fiumicino Leonardo da Vinci International Airport', 'Italy'],
 'NAP': ['Napoli', 'Naples International Airport', 'Italy'],
 'PSA': ['Pisa', 'Pisa International Airport', 'Italy'],
 'LJU': ['Ljubljana', 'Ljubljana Joze Pucnik Airport', 'Slovenia'],
 'PRG': ['Prague', 'Vaclav Havel Airport Prague', 'Czech Republic'],
 'TLV': ['Tel Aviv', 'Ben Gurion International Airport', 'Israel'],
 'ETM': ['Eilat', 'Ramon Airport', 'Israel'],
 'MLA': ['Valletta', 'Malta International Airport', 'Malta'],
 'VIE': ['Vienna', 'Vienna International Airport', 'Austria'],
 'FAO': ['Faro', 'Faro Airport', 'Portugal'],
 'PDL': ['Ponta Delgada', 'Joao Paulo II Airport', 'Portugal'],
 'OPO': ['Porto', 'Francisco de Sa Carneiro Airport', 'Portugal'],
 'LIS': ['Lisbon', 'Humberto Delgado Airport (Lisbon Portela Airport)', 'Portugal'],
 'OTP': ['Bucharest', 'Henri Coanda International Airport', 'Romania'],
 'GVA': ['Geneva', 'Geneva Cointrin International Airport', 'Switzerland'],
 'ZRH': ['Zurich', 'Zurich Airport', 'Switzerland'],
 'ESB': ['Ankara', 'Esenboga International Airport', 'Turkey'],
 'AYT': ['Antalya', 'Antalya International Airport', 'Turkey'],
 'ISL': ['Bakirkoy, Istanbul', 'Istanbul Ataturk Airport', 'Turkey'],
 'ADB': ['Izmir', 'Adnan Menderes International Airport', 'Turkey'],
 'DLM': ['Dalaman', 'Dalaman International Airport', 'Turkey'],
 'BJV': ['Bodrum', 'Milas Bodrum International Airport', 'Turkey'],
 'SAW': ['Pendik, Istanbul', 'Istanbul Sabiha Gokcen International Airport', 'Turkey'],
 'IST': ['Arnavutkoy, Istanbul', 'Istanbul Airport', 'Turkey'],
 'SKP': ['Skopje', 'Skopje International Airport', 'Macedonia, The Former Yugoslav Republic of'],
 'BEG': ['Belgrade', 'Belgrade Nikola Tesla Airport', 'RS'],
 'TGD': ['Podgorica', 'Podgorica Airport / Podgorica Golubovci Airbase', 'ME'],
 'BTS': ['Bratislava', 'M. R. Stefanik Airport', 'Slovakia'],
 'PLS': ['Providenciales', 'Providenciales International Airport', 'Turks and Caicos Islands'],
 'PUJ': ['Punta Cana', 'Punta Cana International Airport', 'Dominican Republic'],
 'SDQ': ['Santo Domingo', 'Las Americas International Airport', 'Dominican Republic'],
 'GUA': ['Guatemala City', 'La Aurora Airport', 'Guatemala'],
 'KIN': ['Kingston', 'Norman Manley International Airport', 'Jamaica'],
 'ACA': ['Acapulco', 'General Juan N Alvarez International Airport', 'Mexico'],
 'GDL': ['Guadalajara', 'Don Miguel Hidalgo Y Costilla International Airport', 'Mexico'],
 'HMO': ['Hermosillo', 'General Ignacio P. Garcia International Airport', 'Mexico'],
 'MEX': ['Mexico City', 'Licenciado Benito Juarez International Airport', 'Mexico'],
 'MZT': ['Mazatlan', 'General Rafael Buelna International Airport', 'Mexico'],
 'PVR': ['Puerto Vallarta', 'Licenciado Gustavo Diaz Ordaz International Airport', 'Mexico'],
 'SJD': ['San Jose del Cabo', 'Los Cabos International Airport', 'Mexico'],
 'TIJ': ['Tijuana', 'General Abelardo L. Rodriguez International Airport', 'Mexico'],
 'CUN': ['Cancun', 'Cancun International Airport', 'Mexico'],
 'PTY': ['Tocumen', 'Tocumen International Airport', 'Panama'],
 'LIR': ['Liberia', 'Guanacaste Airport', 'Costa Rica'],
 'SAL': ['San Salvador (San Luis Talpa)', 'Monsenor Oscar Arnulfo Romero International Airport', 'El Salvador'],
 'PAP': ['Port-au-Prince', 'Toussaint Louverture International Airport', 'Haiti'],
 'HAV': ['Havana', 'Jose Marti International Airport', 'Cuba'],
 'VRA': ['Varadero', 'Juan Gualberto Gomez International Airport', 'Cuba'],
 'GCM': ['Georgetown', 'Owen Roberts International Airport', 'Cayman Islands'],
 'NAS': ['Nassau', 'Lynden Pindling International Airport', 'Bahamas'],
 'BZE': ['Belize City', 'Philip S. W. Goldson International Airport', 'Belize'],
 'RAR': ['Avarua', 'Rarotonga International Airport', 'Cook Islands'],
 'PPT': ['Papeete', "Faa'a International Airport", 'French Polynesia'],
 'VLI': ['Port Vila', 'Bauerfield International Airport', 'Vanuatu'],
 'GEA': ['Noumea', 'Noumea Magenta Airport', 'New Caledonia'],
 'AKL': ['Auckland', 'Auckland International Airport', 'New Zealand'],
 'CHC': ['Christchurch', 'Christchurch International Airport', 'New Zealand'],
 'WLG': ['Wellington', 'Wellington International Airport', 'New Zealand'],
 'BAH': ['Manama', 'Bahrain International Airport', 'Bahrain'],
 'DMM': ['Ad Dammam', 'King Fahd International Airport', 'Saudi Arabia'],
 'JED': ['Jeddah', 'King Abdulaziz International Airport', 'Saudi Arabia'],
 'MED': ['Medina', 'Prince Mohammad Bin Abdulaziz Airport', 'Saudi Arabia'],
 'RUH': ['Riyadh', 'King Khaled International Airport', 'Saudi Arabia'],
 'IKA': ['Tehran', 'Imam Khomeini International Airport', 'Iran, Islamic Republic Of'],
 'THR': ['Tehran', 'Mehrabad International Airport', 'Iran, Islamic Republic Of'],
 'MHD': ['Mashhad', 'Mashhad International Airport', 'Iran, Islamic Republic Of'],
 'SYZ': ['Shiraz', 'Shiraz Shahid Dastghaib International Airport', 'Iran, Islamic Republic Of'],
 'AMM': ['Amman', 'Queen Alia International Airport', 'Jordan'],
 'KWI': ['Kuwait City', 'Kuwait International Airport', 'Kuwait'],
 'BEY': ['Beirut', 'Beirut Rafic Hariri International Airport', 'Lebanon'],
 'DQM': ['Duqm', 'Duqm International Airport', 'Oman'],
 'AUH': ['Abu Dhabi', 'Abu Dhabi International Airport', 'United Arab Emirates'],
 'DXB': ['Dubai', 'Dubai International Airport', 'United Arab Emirates'],
 'DWC': ['Jebel Ali', 'Al Maktoum International Airport', 'United Arab Emirates'],
 'SHJ': ['Sharjah', 'Sharjah International Airport', 'United Arab Emirates'],
 'MCT': ['Muscat', 'Muscat International Airport', 'Oman'],
 'ISB': ['Islamabad', 'Islamabad International Airport', 'Pakistan'],
 'KHI': ['Karachi', 'Jinnah International Airport', 'Pakistan'],
 'BGW': ['Baghdad', 'Baghdad International Airport / New Al Muthana Air Base', 'Iraq'],
 'DAM': ['Damascus', 'Damascus International Airport', 'Syrian Arab Republic'],
 'DOH': ['Doha', 'Hamad International Airport', 'Qatar'],
 'FAI': ['Fairbanks', 'Fairbanks International Airport', 'United States'],
 'ANC': ['Anchorage', 'Ted Stevens Anchorage International Airport', 'United States'],
 'GUM': ['Hagatna, Guam International Airport', 'Antonio B. Won Pat International Airport', 'Guam'],
 'HNL': ['Honolulu', 'Daniel K Inouye International Airport', 'United States'],
 'KHH': ['Kaohsiung (Xiaogang)', 'Kaohsiung International Airport', 'Taiwan, Province of China'],
 'TPE': ['Taipei', 'Taiwan Taoyuan International Airport', 'Taiwan, Province of China'],
 'NRT': ['Tokyo', 'Narita International Airport', 'Japan'],
 'KIX': ['Osaka', 'Kansai International Airport', 'Japan'],
 'CTS': ['Sapporo', 'New Chitose Airport', 'Japan'],
 'FUK': ['Fukuoka', 'Fukuoka Airport', 'Japan'],
 'KOJ': ['Kagoshima', 'Kagoshima Airport', 'Japan'],
 'NGO': ['Tokoname', 'Chubu Centrair International Airport', 'Japan'],
 'ITM': ['Osaka', 'Osaka International Airport', 'Japan'],
 'SDJ': ['Natori', 'Sendai Airport', 'Japan'],
 'HND': ['Tokyo', 'Tokyo Haneda International Airport', 'Japan'],
 'MWX': ['Piseo-ri (Muan)', 'Muan International Airport', 'Korea, Republic of'],
 'CJU': ['Jeju City', 'Jeju International Airport', 'Korea, Republic of'],
 'PUS': ['Busan', 'Gimhae International Airport', 'Korea, Republic of'],
 'ICN': ['Seoul', 'Incheon International Airport', 'Korea, Republic of'],
 'GMP': ['Seoul', 'Gimpo International Airport', 'Korea, Republic of'],
 'OKA': ['Naha', 'Naha Airport / JASDF Naha Air Base', 'Japan'],
 'MNL': ['Manila', 'Ninoy Aquino International Airport', 'Philippines'],
 'DVO': ['Davao', 'Francisco Bangoy International Airport', 'Philippines'],
 'CEB': ['Lapu-Lapu City', 'Mactan Cebu International Airport', 'Philippines'],
 'GRV': ['Grozny', 'Grozny North Airport', 'Russian Federation'],
 'AEP': ['Buenos Aires', 'Jorge Newbery Airpark', 'Argentina'],
 'EZE': ['Buenos Aires (Ezeiza)', 'Ministro Pistarini International Airport', 'Argentina'],
 'BEL': ['Belem', 'Val de Cans/Julio Cezar Ribeiro International Airport', 'Brazil'],
 'BSB': ['Brasilia', 'Presidente Juscelino Kubitschek International Airport', 'Brazil'],
 'CNF': ['Belo Horizonte', 'Tancredo Neves International Airport', 'Brazil'],
 'MAO': ['Manaus', 'Eduardo Gomes International Airport', 'Brazil'],
 'FLN': ['Florianopolis', 'Hercilio Luz International Airport', 'Brazil'],
 'GIG': ['Rio De Janeiro', 'Rio Galeao - Tom Jobim International Airport', 'Brazil'],
 'GRU': ['Sao Paulo', 'Guarulhos - Governador Andre Franco Montoro International Airport', 'Brazil'],
 'SSA': ['Salvador', 'Deputado Luiz Eduardo Magalhaes International Airport', 'Brazil'],
 'SCL': ['Santiago', 'Comodoro Arturo Merino Benitez International Airport', 'Chile'],
 'GYE': ['Guayaquil', 'Jose Joaquin de Olmedo International Airport', 'Ecuador'],
 'UIO': ['Quito', 'Mariscal Sucre International Airport', 'Ecuador'],
 'BOG': ['Bogota', 'El Dorado International Airport', 'Colombia'],
 'VVI': ['Santa Cruz', 'Viru Viru International Airport', 'Bolivia'],
 'PBM': ['Zandery', 'Johan Adolf Pengel International Airport', 'Suriname'],
 'CAY': ['Matoury', 'Cayenne - Felix Eboue Airport', 'French Guiana'],
 'LIM': ['Lima', 'Jorge Chavez International Airport', 'Peru'],
 'CUZ': ['Cusco', 'Alejandro Velasco Astete International Airport', 'Peru'],
 'MVD': ['Montevideo', 'Carrasco International /General C L Berisso Airport', 'Uruguay'],
 'BLA': ['Barcelona', 'General Jose Antonio Anzoategui International Airport', 'Venezuela'],
 'CCS': ['Caracas', 'Simon Bolivar International Airport', 'Venezuela'],
 'FDF': ['Fort-de-France', 'Martinique Aime Cesaire International Airport', 'Martinique'],
 'PTP': ['Pointe-a-Pitre', 'Pointe-a-Pitre Le Raizet International  Airport', 'Guadeloupe'],
 'SJU': ['San Juan', 'Luis Munoz Marin International Airport', 'Puerto Rico'],
 'UVF': ['Vieux Fort', 'Hewanorra International Airport', 'Saint Lucia'],
 'NBE': ['Enfidha', 'Enfidha - Hammamet International Airport', 'Tunisia'],
 'AUA': ['Oranjestad', 'Queen Beatrix International Airport', 'Aruba'],
 'BON': ['Kralendijk, Bonaire', 'Flamingo International Airport', 'BQ'],
 'CUR': ['Willemstad', 'Hato International Airport', 'CW'],
 'SXM': ['Saint Martin', 'Princess Juliana International Airport', 'SX'],
 'ALA': ['Almaty', 'Almaty Airport', 'Kazakhstan'],
 'NQZ': ['Nur-Sultan', 'Nursultan Nazarbayev International Airport', 'Kazakhstan'],
 'FRU': ['Bishkek', 'Manas International Airport', 'Kyrgyzstan'],
 'HSA': ['', 'Hazrat Sultan International Airport', 'Kazakhstan'],
 'GYD': ['Baku', 'Heydar Aliyev International Airport', 'Azerbaijan'],
 'EVN': ['Yerevan', 'Zvartnots International Airport', 'Armenia'],
 'TBS': ['Tbilisi', 'Tbilisi International Airport', 'Georgia'],
 'VVO': ['Artyom', 'Vladivostok International Airport', 'Russian Federation'],
 'KBP': ['Kiev', 'Boryspil International Airport', 'Ukraine'],
 'LWO': ['Lviv', 'Lviv International Airport', 'Ukraine'],
 'LED': ['St. Petersburg', 'Pulkovo Airport', 'Russian Federation'],
 'MSQ': ['Minsk', 'Minsk National Airport', 'Belarus'],
 'KJA': ['Krasnoyarsk', 'Krasnoyarsk International Airport', 'Russian Federation'],
 'OVB': ['Novosibirsk', 'Novosibirsk Tolmachevo Airport', 'Russian Federation'],
 'ROV': ['Rostov-on-Don', 'Platov International Airport', 'Russian Federation'],
 'AER': ['Sochi', 'Sochi International Airport', 'Russian Federation'],
 'SVX': ['Yekaterinburg', 'Koltsovo Airport', 'Russian Federation'],
 'ASB': ['Ashgabat', 'Ashgabat International Airport', 'Turkmenistan'],
 'TAS': ['Tashkent', 'Tashkent International Airport', 'Uzbekistan'],
 'ZIA': ['Moscow', 'Zhukovsky International Airport', 'Russian Federation'],
 'DME': ['Moscow', 'Domodedovo International Airport', 'Russian Federation'],
 'SVO': ['Moscow', 'Sheremetyevo International Airport', 'Russian Federation'],
 'VKO': ['Moscow', 'Vnukovo International Airport', 'Russian Federation'],
 'KZN': ['Kazan', 'Kazan International Airport', 'Russian Federation'],
 'GSV': ['Saratov', 'Gagarin International Airport', 'Russian Federation'],
 'UFA': ['Ufa', 'Ufa International Airport', 'Russian Federation'],
 'KUF': ['Samara', 'Kurumoch International Airport', 'Russian Federation'],
 'BOM': ['Mumbai', 'Chhatrapati Shivaji International Airport', 'India'],
 'GOI': ['Vasco da Gama', 'Dabolim Airport', 'India'],
 'CMB': ['Colombo', 'Bandaranaike International Colombo Airport', 'Sri Lanka'],
 'HRI': ['', 'Mattala Rajapaksa International Airport', 'Sri Lanka'],
 'PNH': ['Phnom Penh (Pou Senchey)', 'Phnom Penh International Airport', 'Cambodia'],
 'REP': ['Siem Reap', 'Siem Reap International Airport', 'Cambodia'],
 'CCU': ['Kolkata', 'Netaji Subhash Chandra Bose International Airport', 'India'],
 'DAC': ['Dhaka', 'Hazrat Shahjalal International Airport', 'Bangladesh'],
 'HKG': ['Hong Kong', 'Hong Kong International Airport', 'Hong Kong'],
 'DEL': ['New Delhi', 'Indira Gandhi International Airport', 'India'],
 'MFM': ['Freguesia de Nossa Senhora do Carmo (Taipa)', 'Macau International Airport', 'Macao'],
 'KTM': ['Kathmandu', 'Tribhuvan International Airport', 'Nepal'],
 'BLR': ['Bangalore', 'Kempegowda International Airport', 'India'],
 'COK': ['Kochi', 'Cochin International Airport', 'India'],
 'HYD': ['Hyderabad', 'Rajiv Gandhi International Airport', 'India'],
 'MAA': ['Chennai', 'Chennai International Airport', 'India'],
 'TRV': ['Thiruvananthapuram', 'Trivandrum International Airport', 'India'],
 'MLE': ['Male', 'Male International Airport', 'Maldives'],
 'DMK': ['Bangkok', 'Don Mueang International Airport', 'Thailand'],
 'BKK': ['Bangkok', 'Suvarnabhumi Airport', 'Thailand'],
 'CNX': ['Chiang Mai', 'Chiang Mai International Airport', 'Thailand'],
 'HKT': ['Phuket', 'Phuket International Airport', 'Thailand'],
 'HAN': ['Soc Son, Hanoi', 'Noi Bai International Airport', 'Viet Nam'],
 'SGN': ['Ho Chi Minh City', 'Tan Son Nhat International Airport', 'Viet Nam'],
 'MDL': ['Mandalay', 'Mandalay International Airport', 'Myanmar'],
 'RGN': ['Yangon', 'Yangon International Airport', 'Myanmar'],
 'UPG': ['Ujung Pandang-Celebes Island', 'Hasanuddin International Airport', 'Indonesia'],
 'DPS': ['Denpasar-Bali Island', 'Ngurah Rai (Bali) International Airport', 'Indonesia'],
 'SUB': ['Surabaya', 'Juanda International Airport', 'Indonesia'],
 'BWN': ['Bandar Seri Begawan', 'Brunei International Airport', 'Brunei Darussalam'],
 'CGK': ['Jakarta', 'Soekarno-Hatta International Airport', 'Indonesia'],
 'KUL': ['Kuala Lumpur', 'Kuala Lumpur International Airport', 'Malaysia'],
 'SIN': ['Singapore', 'Singapore Changi Airport', 'Singapore'],
 'BNE': ['Brisbane', 'Brisbane International Airport', 'Australia'],
 'MEL': ['Melbourne', 'Melbourne International Airport', 'Australia'],
 'YNT': ['Yantai', 'Yantai Penglai International Airport', 'China'],
 'ADL': ['Adelaide', 'Adelaide International Airport', 'Australia'],
 'PER': ['Perth', 'Perth International Airport', 'Australia'],
 'SYD': ['Sydney', 'Sydney Kingsford Smith International Airport', 'Australia'],
 'PEK': ['Beijing', 'Beijing Capital International Airport', 'China'],
 'PKX': ['Beijing', 'Beijing Daxing International Airport', 'China'],
 'HET': ['Hohhot', 'Baita International Airport', 'China'],
 'TSN': ['Tianjin', 'Tianjin Binhai International Airport', 'China'],
 'TYN': ['Taiyuan', 'Taiyuan Wusu Airport', 'China'],
 'CAN': ['Guangzhou (Huadu)', 'Guangzhou Baiyun International Airport', 'China'],
 'CSX': ['Changsha', 'Changsha Huanghua International Airport', 'China'],
 'KWL': ['Guilin (Lingui)', 'Guilin Liangjiang International Airport', 'China'],
 'NNG': ['Nanning (Jiangnan)', 'Nanning Wuxu Airport', 'China'],
 'SZX': ["Shenzhen (Bao'an)", "Shenzhen Bao'an International Airport", 'China'],
 'CGO': ['Zhengzhou', 'Zhengzhou Xinzheng International Airport', 'China'],
 'WUH': ['Wuhan', 'Wuhan Tianhe International Airport', 'China'],
 'HAK': ['Haikou (Meilan)', 'Haikou Meilan International Airport', 'China'],
 'SYX': ['Sanya (Tianya)', 'Sanya Phoenix International Airport', 'China'],
 'XIY': ["Xi'an", "Xi'an Xianyang International Airport", 'China'],
 'UBN': ['Ulaanbaatar (Sergelen)', 'Ulaanbaatar Chinggis Khaan International Airport', 'Mongolia'],
 'KMG': ['Kunming', 'Kunming Changshui International Airport', 'China'],
 'XMN': ['Xiamen', 'Xiamen Gaoqi International Airport', 'China'],
 'FOC': ['Fuzhou', 'Fuzhou Changle International Airport', 'China'],
 'HGH': ['Hangzhou', 'Hangzhou Xiaoshan International Airport', 'China'],
 'TNA': ['Jinan', 'Jinan Yaoqiang International Airport', 'China'],
 'NGB': ['Ningbo', 'Ningbo Lishe International Airport', 'China'],
 'NKG': ['Nanjing', 'Nanjing Lukou International Airport', 'China'],
 'PVG': ['Shanghai (Pudong)', 'Shanghai Pudong International Airport', 'China'],
 'SHA': ['Shanghai (Minhang)', 'Shanghai Hongqiao International Airport', 'China'],
 'WNZ': ['Wenzhou', 'Wenzhou Longwan International Airport', 'China'],
 'CKG': ['Chongqing', 'Chongqing Jiangbei International Airport', 'China'],
 'KWE': ['Guiyang', 'Longdongbao Airport', 'China'],
 'CTU': ['Chengdu', 'Chengdu Shuangliu International Airport', 'China'],
 'URC': ['Urumqi', 'Urumqi Diwopu International Airport', 'China'],
 'HRB': ['Harbin', 'Harbin Taiping International Airport', 'China'],
 'DLC': ['Ganjingzi, Dalian', 'Dalian Zhoushuizi International Airport', 'China'],
 'SHE': ['Hunnan, Shenyang', 'Shenyang Taoxian International Airport', 'China']
 }